services:
  db:
    image: postgres:15
    container_name: trabalho_postgres
    environment:
      POSTGRES_DB: trabalho_es
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_secreta
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: tomcat:10.1-jdk17
    container_name: trabalho_tomcat
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./MyEnderecoServicos/target/endereco.war:/usr/local/tomcat/webapps/endereco.war
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"

  testes:
    image: maven:3.8.5-openjdk-17
    container_name: trabalho_testes
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: mvn test -DfailIfNoTests=false
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./Frontend
    container_name: trabalho_frontend_endereco
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://app:8080/endereco
    depends_on:
      - app

  # FUTURO: frontend-estudo-a
  # frontend-estudo-a:
  #   build: ./FrontendEstudoA
  #   ports: ["5174:5173"]
  #   environment:
  #     - VITE_API_URL=http://app:8080/estudoA