services:
  db:
    image: postgres:15
    container_name: trabalho_postgres
    environment:
      POSTGRES_DB: trabalho_es
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_secreta
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trabalho_tomcat
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"

  testes:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: trabalho_testes
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: mvn test -DfailIfNoTests=false
    depends_on:
      db:
        condition: service_healthy

  frontend_endereco:
    build: ./EnderecoFront
    container_name: trabalho_frontend_endereco
    ports:
      - "5173:5173"
    volumes:
      - ./EnderecoFront:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - app

  frontend_aluguel:
    build: ./AluguelFront
    container_name: trabalho_frontend_aluguel
    ports:
      - "5174:5173"
    volumes:
      - ./AluguelFront:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - app